plugins {
    id 'maven-publish'
}

def mcVersion = providers.gradleProperty('mcVersion').orElse('26.3').get()
def versionFile = file("versions/${mcVersion}.properties")

if (!versionFile.exists()) {
    throw new GradleException("Unsupported Minecraft version: ${mcVersion}")
}

def mcProperties = new Properties()

versionFile.withInputStream {
    mcProperties.load(it)
}

mcProperties.each { key, value ->
    ext[key.toString()] = value.toString()
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    version = project.mod_version
    group = project.mod_group

    repositories {
        mavenCentral()

        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }

        maven {
            name = "NeoForged"
            url = "https://maven.neoforged.net/releases"
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = Integer.parseInt(project.java_version)
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(project.java_version)
        }

        withSourcesJar()
    }

    sourceSets {
        main {
            resources {
                if (vl_supports_poplar != 'true') {
                    exclude 'assets/villager-lock/blockstates/villagerpost_poplar.json'
                    exclude 'assets/villager-lock/items/villagerpost_poplar.json'
                    exclude 'assets/villager-lock/models/block/villagerpost_poplar.json'
                    exclude 'data/villager-lock/advancement/recipes/villagerpost_poplar.json'
                    exclude 'data/villager-lock/loot_table/blocks/villagerpost_poplar.json'
                    exclude 'data/villager-lock/recipe/villagerpost_poplar.json'
                    // Has on common\src\main\resources\data\minecraft\tags\block\mineable\axe.json
                    // Has on common\src\main\resources\assets\villager-lock\lang/*.json
                    // No minecraft errors about non registered blocks, so no need to rewrite the specified files to remove the poplar post
                }
            }
        }
    }
}

tasks.register('copyArtifacts', Copy) {
    dependsOn ':fabric:build', ':neoforge:build'

    from project(':fabric').layout.buildDirectory.dir('libs')
    from project(':neoforge').layout.buildDirectory.dir('libs')

    into layout.buildDirectory.dir('libs')
}

tasks.register('build') {
    dependsOn ':fabric:build', ':neoforge:build'
    finalizedBy 'copyArtifacts'
}