plugins {
    id 'maven-publish'
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    version = project.mod_version
    group = project.mod_group

    repositories {
        mavenCentral()
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        maven {
            name = "NeoForged"
            url = "https://maven.neoforged.net/releases"
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = Integer.parseInt(project.java_version)
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(project.java_version)
        }
        withSourcesJar()
    }
}

tasks.register('copyArtifacts', Copy) {
    from subprojects.collect { it.layout.buildDirectory.dir('libs') }
    into layout.buildDirectory.dir('libs')
}

tasks.named('build') {
    finalizedBy 'copyArtifacts'
}
