# Environment
minecraft_version=26.3
minecraft_version_max=26.3
java_version=25

# Fabric
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.160.6+26.3

# NeoForge
neoforge_version=26.3.0.1-beta
moddevgradle_version=2.0.147