modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "villagerlock"
version = "${version}"
displayName = "Villager Lock"
authors = "UkrainianCoder, xiader45"
description = '''Villager Lock adds the Villager Post, a block designed to lock villagers to their job sites, ensuring perfectly organized and efficient trading halls!'''
logoFile = "assets/villager-lock/icon.png"

[[mixins]]
config = "villager-lock.mixins.json"

[[dependencies.villagerlock]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.villagerlock]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"
